# config/packages/sylius_resource.yaml
sylius_resource:
    resources:
        app.produit:
            driver: doctrine/orm # You can use also different driver here
            classes:
                model: App\Entity\Produit
                repository: App\Repository\ProduitRepository
                form: App\Form\ProduitType
              
        app.imageProduit:
            driver: doctrine/orm
            classes:
                model: App\Entity\ImageProduit
                 

    
